export const members = [
  {
    id: 1,
    name: "음상훈",
    photoUrl: "/assets/images/interview/eumsanghoon.jpg",
    role: "대표, 프론트엔드, 백엔드",
    generations: [12],
    description: "Make likelion great again",
  },
  {
    id: 2,
    name: "이종원",
    photoUrl: "/assets/images/interview/leejongwon.jpg",
    role: "대표, 프론트엔드, 백엔드",
    generations: [13],
    description:
      "운영진과 함께 아기사자들에게 의미있는 동아리 활동을 만들겠습니다!",
  },
  {
    id: 3,
    name: "윤현주",
    photoUrl: "/assets/images/interview/yoonhyeonju.jpg",
    role: "부대표, 기획/디자인",
    generations: [12, 13],
    description: "아기사자분들이 믿고 따라오실 수 있는 운영진이 되겠습니다🤩",
  },
  {
    id: 4,
    name: "김선후",
    photoUrl: "/assets/images/interview/kimseonhu.jpg",
    role: "프론트엔드, 백엔드",
    generations: [12, 13],
    description: "쉽게 설명할 수 있을 때 비로소 내 것이 된다!",
  },
  {
    id: 5,
    name: "송재현",
    photoUrl: "/assets/images/interview/songjaehyeon.jpg",
    role: "백엔드",
    generations: [12, 13],
    description: "1년동안 후회 없이 불태우자🔥",
  },
  {
    id: 6,
    name: "오승아",
    photoUrl: "/assets/images/interview/ohseunga.jpg",
    role: "기획/디자인",
    generations: [12],
    description: "우리가 함께한 1년, 후회 없이 전진했던 시간",
  },
  {
    id: 7,
    name: "김승민",
    photoUrl: "/assets/images/interview/kimseungmin.jpg",
    role: "백엔드",
    generations: [13],
    description: "함께 성장하는 시간으로 만들기 위해 최선을 다하겠습니다",
  },
  {
    id: 8,
    name: "정재민",
    photoUrl: "/assets/images/interview/jeongjaemin.jpg",
    role: "기획/디자인",
    generations: [13],
    description:
      "팀원들과 함께 협력하며 성장하고, 멋진 결과를 만들어가도록 하겠습니다.",
  },
  {
    id: 9,
    name: "송현서",
    photoUrl: "/assets/images/interview/songhyeonse.jpg",
    role: "기획/디자인",
    generations: [13],
    description:
      "멋사의 손발이 되어 여러분들께 성장의 발판을 마련해드리겠습니다!",
  },
  {
    id: 10,
    name: "김세현",
    photoUrl: "/assets/images/interview/kimsehyun.jpg",
    role: "프론트엔드",
    generations: [13],
    description: "아자아자 화이팅",
  },
  {
    id: 11,
    name: "송가은",
    photoUrl: "/assets/images/interview/songgaeun.jpg",
    role: "프론트엔드",
    generations: [13],
    description: "멋사와 함께 즐거움과 배움을 찾는 동아리가 되었으면 합니다",
  },
  {
    id: 12,
    name: "이가은",
    photoUrl: "/assets/images/interview/leegaeun.jpg",
    role: "프론트엔드",
    generations: [13],
    description: "2025년 한해를 불태워보겠습니다!",
  },
];
